/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bean.TypeRenumeration;
import controller.TypeRenumerationController;
import javax.swing.DefaultListModel;

/**
 *
 * @author ATH
 */
public class AdministrationTypeRenumeration extends javax.swing.JDialog {

    /**
     * Creates new form AdministrationTypeRenumeration
     * @param parent
     * @param modal
     */
    public AdministrationTypeRenumeration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        typeRenumerationController = new TypeRenumerationController();
        initComponents();
        initList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMTextFull_libelle = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_type_renumeration = new javax.swing.JList<>();
        rSButtonRiple_creation_modification = new rojeru_san.RSButtonRiple();
        jSeparator1 = new javax.swing.JSeparator();
        rSButtonRiple_actualiser = new rojeru_san.RSButtonRiple();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des types de rénumeration");
        setResizable(false);

        rSMTextFull_libelle.setPlaceholder("");

        jList_type_renumeration.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_type_renumeration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_type_renumerationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_type_renumeration);

        rSButtonRiple_creation_modification.setText("Créer");
        rSButtonRiple_creation_modification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_creation_modificationActionPerformed(evt);
            }
        });

        rSButtonRiple_actualiser.setText("Actualiser");
        rSButtonRiple_actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_actualiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSButtonRiple_creation_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rSMTextFull_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rSButtonRiple_actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonRiple_actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonRiple_creation_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMTextFull_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList_type_renumerationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_type_renumerationMouseClicked
        if(jList_type_renumeration.getSelectedIndex() > -1){
            rSButtonRiple_creation_modification.setText("Modifier");
            //TypeRenumeration type = typeRenumerationController.getType(jList_type_renumeration.getSelectedValue());
            rSMTextFull_libelle.setText(jList_type_renumeration.getSelectedValue());
        }else{
            rSButtonRiple_creation_modification.setText("Créer");
        }
    }//GEN-LAST:event_jList_type_renumerationMouseClicked

    private void rSButtonRiple_creation_modificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_creation_modificationActionPerformed
        if(rSButtonRiple_creation_modification.getText().equals("Modifier")){
            //modification id_type, libelle
            TypeRenumeration type = typeRenumerationController.getType(jList_type_renumeration.getSelectedValue());
//            rSMTextFull_libelle.setText(jList_type_renumeration.getSelectedValue());
            typeRenumerationController.updateType(type.getId(), rSMTextFull_libelle.getText());
            initList();
            rSMTextFull_libelle.setText("");
        }else{
            //creation libelle
            typeRenumerationController.addType(rSMTextFull_libelle.getText());
           initList(); 
        }
    }//GEN-LAST:event_rSButtonRiple_creation_modificationActionPerformed

    private void rSButtonRiple_actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_actualiserActionPerformed
        initList();
        rSButtonRiple_creation_modification.setText("Créer");
    }//GEN-LAST:event_rSButtonRiple_actualiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationTypeRenumeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationTypeRenumeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationTypeRenumeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationTypeRenumeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministrationTypeRenumeration dialog = new AdministrationTypeRenumeration(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private final TypeRenumerationController typeRenumerationController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList_type_renumeration;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private rojeru_san.RSButtonRiple rSButtonRiple_actualiser;
    private rojeru_san.RSButtonRiple rSButtonRiple_creation_modification;
    private rojeru_san.RSMTextFull rSMTextFull_libelle;
    // End of variables declaration//GEN-END:variables

    private void initList(){
        jList_type_renumeration.removeAll();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        typeRenumerationController.getTypes().forEach((t) -> {
            listModel.addElement(t.getLibelle());
        });
        jList_type_renumeration.setModel(listModel);
    }
}
