/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bean.AvantageEnNature;
import bean.Personnel;
import controller.AvantageEnNatureController;
import controller.PersonnelController;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import main.NumberRenderer;

/**
 *
 * @author ATH
 */
public class AvantageEnNatureDialog extends javax.swing.JDialog {

    /**
     * Creates new form AvantageEnNatureDialog
     * @param parent
     * @param modal
     */
    public AvantageEnNatureDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        personnelController = new PersonnelController();
        avantageEnNatureController = new AvantageEnNatureController();
        initComponents();
        initCBPersonnel();
        logement = 20000;
        ameublement = logement/3;
        electricite = 50000;
        eau = 15000;
        telephone = 20000;
        vehicule = 20000;
        initTable();
    }
    
    /**
     *
     * @param parent
     * @param modal
     * @param id_personnels
     */
    public AvantageEnNatureDialog(java.awt.Frame parent, boolean modal, ArrayList<Integer> id_personnels) {
        super(parent, modal);
        id_avantage = 0;
        this.id_personnels = id_personnels;
        personnelController = new PersonnelController();
        avantageEnNatureController = new AvantageEnNatureController();
        initComponents();
        initCBPersonnel();
        logement = 20000;
        ameublement = logement/3;
        electricite = 50000;
        eau = 15000;
        telephone = 20000;
        vehicule = 20000;
        initTable();
    }
    
    /**
     *
     * @param parent
     * @param modal
     * @param id_avantage
     */
    public AvantageEnNatureDialog(java.awt.Frame parent, boolean modal, int id_avantage) {
        super(parent, modal);
        this.id_avantage = id_avantage;
        id_personnels = new ArrayList<>();
        personnelController = new PersonnelController();
        avantageEnNatureController = new AvantageEnNatureController();
        id_personnels.add(avantageEnNatureController.getAvantageEnNature(id_avantage).getId_personnel());
        initComponents();
        initCBPersonnel();
        logement = 20000;
        ameublement = logement/3;
        electricite = 50000;
        eau = 15000;
        telephone = 20000;
        vehicule = 20000;
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSComboMetro_personnels = new rojerusan.RSComboMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_avantages = new javax.swing.JTable();
        rSButtonRiple_valider = new rojeru_san.RSButtonRiple();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des avantages en nature");
        setResizable(false);

        jLabel1.setText("Personnel(s)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Liste des avantages en nature"));

        jTable_avantages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "LIBELLE", "MONTANT"
            }
        ));
        jScrollPane1.setViewportView(jTable_avantages);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSButtonRiple_valider.setText("Valider");
        rSButtonRiple_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSComboMetro_personnels, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonRiple_valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSComboMetro_personnels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple_valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_validerActionPerformed
        if(id_avantage != 0){
//            id_personnels.forEach(id -> {
//                avantageEnNatureController.updateAvantageEnNature(id_avantage, (int)jTable_avantages.getValueAt(0, 1), (int)jTable_avantages.getValueAt(1, 1), (int)jTable_avantages.getValueAt(2, 1), (int)jTable_avantages.getValueAt(3, 1), (int)jTable_avantages.getValueAt(4, 1), (int)jTable_avantages.getValueAt(5, 1), id);
//            });
        }else{
            id_personnels.forEach(id -> {
                try {
                    avantageEnNatureController.addAvantageEnNature(
                        Integer.parseInt(jTable_avantages.getValueAt(0, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", "")), 
                        Integer.parseInt(jTable_avantages.getValueAt(1, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", "")), 
                        Integer.parseInt(jTable_avantages.getValueAt(2, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", "")), 
                        Integer.parseInt(jTable_avantages.getValueAt(3, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", "")), 
                        Integer.parseInt(jTable_avantages.getValueAt(4, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", "")), 
                        Integer.parseInt(jTable_avantages.getValueAt(5, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", "")), 
                        id
                    );
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Saisir un bon montant ", "Format incorrect !", JOptionPane.WARNING_MESSAGE);
                    System.out.println("Erreur " + e.getMessage());
                }
                
            });
        }
        JOptionPane.showMessageDialog(null, "Opération effectuée avec succes ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_rSButtonRiple_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvantageEnNatureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvantageEnNatureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvantageEnNatureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvantageEnNatureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AvantageEnNatureDialog dialog = new AvantageEnNatureDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    private ArrayList<Integer> id_personnels;
    private final PersonnelController personnelController;
    private int id_avantage;
    private final AvantageEnNatureController avantageEnNatureController;
    int logement, ameublement, electricite, eau, telephone, vehicule;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_avantages;
    private rojeru_san.RSButtonRiple rSButtonRiple_valider;
    private rojerusan.RSComboMetro rSComboMetro_personnels;
    // End of variables declaration//GEN-END:variables



    private void initTable(){
        String entete[] = {"LIBELLE", "MONTANT"};
        DefaultTableModel dt=new DefaultTableModel(null,entete);
        dt.setRowCount(0);
        Object colonne[] = new Object[2];
        //logement
        if(id_avantage == 0){
            colonne[0] = "Logement";
            colonne[1] = logement;
            dt.addRow(colonne);
            //ameublemeent
            colonne = new Object[2];
            colonne[0] = "Ameublement";
            colonne[1] = ameublement;
            dt.addRow(colonne);
            //electricite
            colonne = new Object[2];
            colonne[0] = "Electricité";
            colonne[1] = electricite;
            dt.addRow(colonne);
            //eau
            colonne = new Object[2];
            colonne[0] = "Eau";
            colonne[1] = eau;
            dt.addRow(colonne);
            //telephone
            colonne = new Object[2];
            colonne[0] = "Téléphone";
            colonne[1] = telephone;
            dt.addRow(colonne);
            //vehicule
            colonne = new Object[2];
            colonne[0] = "Véhicule";
            colonne[1] = vehicule;
        }else{
            AvantageEnNature av = avantageEnNatureController.getAvantageEnNature(id_avantage);
            colonne[0] = "Logement";
            colonne[1] = av.getLogement();
            dt.addRow(colonne);
            //ameublemeent
            colonne = new Object[2];
            colonne[0] = "Ameublement";
            colonne[1] = av.getAmeublement();
            dt.addRow(colonne);
            //electricite
            colonne = new Object[2];
            colonne[0] = "Electricité";
            colonne[1] = av.getElectricite();
            dt.addRow(colonne);
            //eau
            colonne = new Object[2];
            colonne[0] = "Eau";
            colonne[1] = av.getEau();
            dt.addRow(colonne);
            //telephone
            colonne = new Object[2];
            colonne[0] = "Téléphone";
            colonne[1] = av.getTelephone();
            dt.addRow(colonne);
            //vehicule
            colonne = new Object[2];
            colonne[0] = "Véhicule";
            colonne[1] = av.getVehicule();
        }
        dt.addRow(colonne);
        
        this.jTable_avantages.setModel(dt);
        if (jTable_avantages.getColumnModel().getColumnCount() > 0) {
            jTable_avantages.getColumnModel().getColumn(1).setCellRenderer(NumberRenderer.get_FCFA_render());
            jTable_avantages.setRowHeight(30);
            jTable_avantages.getTableHeader().setBackground(new Color(0,112,192));
            jTable_avantages.getTableHeader().setForeground(Color.white);
            jTable_avantages.getTableHeader().setFont(new Font("Cambria Math", Font.BOLD, 13));
            jTable_avantages.setFont(new Font("Cambria Math", Font.BOLD, 12));
            jTable_avantages.getModel().addTableModelListener((TableModelEvent e) -> {
                mise_a_jour_avantage();
            });
        }
    }

    private void initCBPersonnel() {
        rSComboMetro_personnels.removeAllItems();
        id_personnels.forEach(id -> {
            Personnel p = personnelController.getPersonnel(id);
            System.out.println(id);
            rSComboMetro_personnels.addItem(p.getNom_prenom());
        });
    }

    private void mise_a_jour_avantage() {
        int row = jTable_avantages.getSelectedRow();
        if(id_avantage == 0){
            switch(row){
                case 0:
                    logement = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                    ameublement = logement/3;
                    break;
                case 1:
                    ameublement = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                    break;
                case 2:
                    electricite = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                    break;
                case 3:
                    eau = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                    break;
                case 4:
                    telephone = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                    break;
                case 5:
                    vehicule = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                    break;
                default:
                    break;
            }
            initTable();
        }else{
            String libelle;
            int montant;
            switch(row){
                case 0:
                    libelle = "logement";
                    break;
                case 1:
                    libelle = "ameublement";
                    break;
                case 2:
                    libelle = "electricite";
                    break;
                case 3:
                    libelle = "eau";
                    break;
                case 4:
                    libelle = "telephone";
                    break;
                case 5:
                    libelle = "vehicule";
                    break;
                default:
                    libelle = "";
                    break;        
            }
            try {
                montant = Integer.parseInt(jTable_avantages.getValueAt(row, 1).toString().trim().replaceAll(" ", "").replaceAll("FCFA", ""));
                avantageEnNatureController.update(id_avantage, libelle, montant);
                initTable();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Saisir un bon montant ", "Format incorrect !", JOptionPane.WARNING_MESSAGE);
                System.out.println("Erreur " + e.getMessage());
            }
        }
        
        
    }
}
