/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import bean.Abattement;
import controller.AbattementController;
import controller.PersonnelController;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.dialog.AbattementDialog;

/**
 *
 * @author ATH
 */
public class AbattementPanel extends javax.swing.JPanel {

    /**
     * Creates new form AvantageEnNaturePanel
     */
    public AbattementPanel() {
        abattementController = new AbattementController();
        personnelController = new PersonnelController();
        initComponents();
        initTable();
        initNew();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        menu_item_update_abattement = new javax.swing.JMenuItem();
        menu_item_remove_abattement = new javax.swing.JMenuItem();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_abattement = new javax.swing.JTable();
        rSButtonRiple_ajouter = new rojeru_san.RSButtonRiple();
        rSButtonRiple_modifier_supprimer = new rojeru_san.RSButtonRiple();
        rSMTextFull_rechercher = new rojeru_san.RSMTextFull();

        menu_item_update_abattement.setText("Mettre à jour ces taux d'abattements");
        menu_item_update_abattement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_update_abattementActionPerformed(evt);
            }
        });
        popup.add(menu_item_update_abattement);

        menu_item_remove_abattement.setText("Retirer les taux d'abattements");
        menu_item_remove_abattement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_remove_abattementActionPerformed(evt);
            }
        });
        popup.add(menu_item_remove_abattement);

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ressources/bo.jpg"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des taux d'abattement par personnel"));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        jTable_abattement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "NOM ET PRENOM", "CHARGE PROFESSIONNELLE", "CHARGE FAMILIALE", "RETENUE CNSS", "CHARGE DEPAYSEM.", "CHARGE PATRONALE", "ID"
            }
        ));
        jTable_abattement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable_abattementMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_abattement);
        if (jTable_abattement.getColumnModel().getColumnCount() > 0) {
            jTable_abattement.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_abattement.getColumnModel().getColumn(0).setPreferredWidth(35);
            jTable_abattement.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable_abattement.getColumnModel().getColumn(2).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(2).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(3).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(3).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(4).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(4).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(5).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(5).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(5).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(6).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(6).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(6).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(7).setMinWidth(5);
            jTable_abattement.getColumnModel().getColumn(7).setPreferredWidth(5);
            jTable_abattement.getColumnModel().getColumn(7).setMaxWidth(5);
        }

        rSButtonRiple_ajouter.setText("Mettre à jour");
        rSButtonRiple_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_ajouterActionPerformed(evt);
            }
        });

        rSButtonRiple_modifier_supprimer.setText("Supprimer");
        rSButtonRiple_modifier_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_modifier_supprimerActionPerformed(evt);
            }
        });

        rSMTextFull_rechercher.setPlaceholder("Rechercher");

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGroup(rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rSPanelImage1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(rSPanelImage1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(rSMTextFull_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(rSButtonRiple_modifier_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButtonRiple_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonRiple_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple_modifier_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMTextFull_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_update_abattementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_update_abattementActionPerformed
        updateAvantage();
    }//GEN-LAST:event_menu_item_update_abattementActionPerformed

    private void menu_item_remove_abattementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_remove_abattementActionPerformed
        removeAvantage();
    }//GEN-LAST:event_menu_item_remove_abattementActionPerformed

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        popupAction(evt);
        if(evt.isPopupTrigger() && evt.getComponent() instanceof JScrollPane){
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
            popup.setVisible(true);
        }
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void jTable_abattementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_abattementMouseReleased
        popupAction(evt);
        if(evt.isPopupTrigger() && evt.getComponent() instanceof JTable){
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
            popup.setVisible(true);
        }
    }//GEN-LAST:event_jTable_abattementMouseReleased

    private void rSButtonRiple_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_ajouterActionPerformed
        if(rSButtonRiple_ajouter.getText().equals("Ajouter")){
            //
        }else{
            updateAvantage();
        }
    }//GEN-LAST:event_rSButtonRiple_ajouterActionPerformed

    private void rSButtonRiple_modifier_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_modifier_supprimerActionPerformed
        removeAvantage();
    }//GEN-LAST:event_rSButtonRiple_modifier_supprimerActionPerformed

    private final AbattementController abattementController;
    private final PersonnelController personnelController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_abattement;
    private javax.swing.JMenuItem menu_item_remove_abattement;
    private javax.swing.JMenuItem menu_item_update_abattement;
    private javax.swing.JPopupMenu popup;
    private rojeru_san.RSButtonRiple rSButtonRiple_ajouter;
    private rojeru_san.RSButtonRiple rSButtonRiple_modifier_supprimer;
    private rojeru_san.RSMTextFull rSMTextFull_rechercher;
    private rojerusan.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables

    private void popupAction(java.awt.event.MouseEvent evt) {
        int r = jTable_abattement.rowAtPoint(evt.getPoint());
        if(r >=0 && r < jTable_abattement.getRowCount()){
            jTable_abattement.setRowSelectionInterval(r, r);

        }else{
            jTable_abattement.clearSelection();
        }
        int index = jTable_abattement.getSelectedRow();
        if(index < 0){
            menu_item_remove_abattement.setEnabled(false);
            menu_item_update_abattement.setEnabled(false);
            initNew();
        }else{
            menu_item_remove_abattement.setEnabled(true);
            menu_item_update_abattement.setEnabled(true);
            initUpdate();
        }
    }
    private void updateAvantage() {
        int row = jTable_abattement.getSelectedRow();
        if(row < 0){
            return;
        }
        int id_abattement = Integer.parseInt(jTable_abattement.getValueAt(row, 8).toString());
        AbattementDialog abattementDialog = new AbattementDialog(null, true, id_abattement);
        abattementDialog.setVisible(true);
        initTable();
    }
    private void removeAvantage() {
        int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir supprimer les taux d'abattement de " + jTable_abattement.getValueAt(jTable_abattement.getSelectedRow(), 1) + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            abattementController.removeAbattement(Integer.parseInt(jTable_abattement.getValueAt(jTable_abattement.getSelectedRow(), 8).toString()));
        }
        initTable();
    }
    private void initNew() {
        rSButtonRiple_ajouter.setText("");
        rSButtonRiple_ajouter.setBackground(Color.green);
        rSButtonRiple_ajouter.setColorHover(new Color(0,200,0));
        rSButtonRiple_ajouter.setVisible(false);
        
        rSButtonRiple_modifier_supprimer.setText("");
        rSButtonRiple_modifier_supprimer.setBackground(new Color(0,112,192));
        rSButtonRiple_modifier_supprimer.setVisible(false);
    }
    
    private void initUpdate() {
        rSButtonRiple_ajouter.setText("Mettre à jour");
        rSButtonRiple_ajouter.setBackground(Color.orange);
        rSButtonRiple_ajouter.setColorHover(new Color(200,200,0));
        rSButtonRiple_ajouter.setVisible(true);
        
        rSButtonRiple_modifier_supprimer.setText("Suprimer");
        rSButtonRiple_modifier_supprimer.setBackground(Color.red);
        rSButtonRiple_modifier_supprimer.setColorHover(new Color(153,102,0));
        rSButtonRiple_modifier_supprimer.setVisible(true);
    }

    private void initTable() {
        initNew();
        String entete[] = {"N°", "NOM ET PRENOM", "CHARGE PROFESSIONNELLE", "CHARGE FAMILIALE", "RETENUE CNSS", "CHARGE DEPAYSEM.", "CHARGE PATRONALE", "RETENUE ANPE", "ID"};
        DefaultTableModel dt = new DefaultTableModel(null,entete);
        dt.setRowCount(0);
        
//        String annee = null, cycle = null, classe = null, rechercher = null, nationalite = null, sexe = null;
//        if(rSComboMetro_annee.getSelectedIndex() > -1){
//            annee = rSComboMetro_annee.getSelectedItem().toString();
//        }
//        if(rSComboMetro_cycle.getSelectedIndex() > -1){
//            cycle = rSComboMetro_cycle.getSelectedItem().toString();
//        }
//        if(rSComboMetro_classe.getSelectedIndex() > -1){
//            classe = rSComboMetro_classe.getSelectedItem().toString();
//        }
//        if(rSMTextFull_recherche.getText().length() > 0){
//            rechercher = rSMTextFull_recherche.getText();
//        }
//        if(rSComboMetro_nationalite.getSelectedIndex() > -1){
//            nationalite = rSComboMetro_nationalite.getSelectedItem().toString();
//        }
//        if(rSComboMetro_sexe.getSelectedIndex() > -1){
//            sexe = rSComboMetro_sexe.getSelectedItem().toString();
//        }
        ArrayList<Abattement> list_abattement = abattementController.getAbattements();
        
        for(int i = 0; i< list_abattement.size(); i++){
            Object colonne[] = new Object[9];
            colonne[0] = i + 1;
            colonne[1] = personnelController.getPersonnel(list_abattement.get(i).getId_personnel()).getNom_prenom();
            colonne[2] = list_abattement.get(i).getCharge_professionnelle() + "%";
            colonne[3] = getChargeFamiliale(personnelController.getPersonnel(list_abattement.get(i).getId_personnel()).getCharge()) + "%";
            colonne[4] = list_abattement.get(i).getRetenue_cnss() + "%";
            colonne[5] = list_abattement.get(i).getCharge_depaysement() + "%";
            colonne[6] = list_abattement.get(i).getCharge_patronale() + "%";
            colonne[7] = list_abattement.get(i).getCharge_anpe() + "%";
            colonne[8] = list_abattement.get(i).getId();
            System.out.println(list_abattement.get(i).getId());
            dt.addRow(colonne);
        }
        
        this.jTable_abattement.setModel(dt);
        if (jTable_abattement.getColumnModel().getColumnCount() > 0) {
            jTable_abattement.getColumnModel().getColumn(0).setMinWidth(35);
            jTable_abattement.getColumnModel().getColumn(0).setPreferredWidth(35);
            jTable_abattement.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable_abattement.getColumnModel().getColumn(2).setMinWidth(180);
            jTable_abattement.getColumnModel().getColumn(2).setPreferredWidth(190);
            jTable_abattement.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable_abattement.getColumnModel().getColumn(3).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(3).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(4).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(4).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(5).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(5).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(5).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(6).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(6).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(6).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(7).setMinWidth(170);
            jTable_abattement.getColumnModel().getColumn(7).setPreferredWidth(180);
            jTable_abattement.getColumnModel().getColumn(7).setMaxWidth(190);
            jTable_abattement.getColumnModel().getColumn(8).setMinWidth(5);
            jTable_abattement.getColumnModel().getColumn(8).setPreferredWidth(5);
            jTable_abattement.getColumnModel().getColumn(8).setMaxWidth(5);
            jTable_abattement.setRowHeight(30);
            jTable_abattement.getTableHeader().setBackground(new Color(0,112,192));
            jTable_abattement.getTableHeader().setForeground(Color.white);
            jTable_abattement.getTableHeader().setFont(new Font("Cambria Math", Font.BOLD, 13));
            jTable_abattement.setFont(new Font("Cambria Math", Font.BOLD, 12));
        }
    }
    
    private double getChargeFamiliale(int charge) {
        switch(charge){
            case 0:
                return 0;
            case 1:
                return 5;
            case 2:
                return 10;
            case 3:
                return 12;
            case 4:
                return 13;
            case 5:
                return 14;
            case 6:
                return 15;
            case 7:
                return 30;
            default:
                return 0;
        }
    }
}
