/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.frame;

import view.dialog.AdministrationTypeRenumeration;
import view.panel.AbattementPanel;
import view.panel.AvantageEnNaturePanel;
import view.panel.NouveauPaiementPanel;
import view.panel.PersonnelPanel;
import view.panel.RenumerationPanel;

/**
 *
 * @author ATH
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_fichier = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu_edition = new javax.swing.JMenu();
        jMenuItem_personnel = new javax.swing.JMenuItem();
        jMenuItem_avantage_en_nature = new javax.swing.JMenuItem();
        jMenuItem_taux_abattement = new javax.swing.JMenuItem();
        jMenuItem_renumeration = new javax.swing.JMenuItem();
        jMenu_paiement = new javax.swing.JMenu();
        jMenuItem_nouveau_paiement = new javax.swing.JMenuItem();
        jMenuItem_historique_paiement = new javax.swing.JMenuItem();
        jMenu_a_propos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tableau de bord");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(900, 450));
        setName("main frame"); // NOI18N

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ressources/gg.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("IT-INNOVATION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel2.setText("INNOVER AU DELA DE L'IMAGINATION !");

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jLabel3.setText("Site web : www.2isolution.com");

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelImage1Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jMenu_fichier.setText("Configuration");

        jMenuItem1.setText("Rénumeration_type");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_fichier.add(jMenuItem1);

        jMenuBar1.add(jMenu_fichier);

        jMenu_edition.setText("Edition");

        jMenuItem_personnel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_personnel.setText("Personnel");
        jMenuItem_personnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_personnelActionPerformed(evt);
            }
        });
        jMenu_edition.add(jMenuItem_personnel);

        jMenuItem_avantage_en_nature.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_avantage_en_nature.setText("Avantage en Nature");
        jMenuItem_avantage_en_nature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_avantage_en_natureActionPerformed(evt);
            }
        });
        jMenu_edition.add(jMenuItem_avantage_en_nature);

        jMenuItem_taux_abattement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_taux_abattement.setText("Taux d'abattement");
        jMenuItem_taux_abattement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_taux_abattementActionPerformed(evt);
            }
        });
        jMenu_edition.add(jMenuItem_taux_abattement);

        jMenuItem_renumeration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_renumeration.setText("Rénumeration accessoire");
        jMenuItem_renumeration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_renumerationActionPerformed(evt);
            }
        });
        jMenu_edition.add(jMenuItem_renumeration);

        jMenuBar1.add(jMenu_edition);

        jMenu_paiement.setText("Paiement");

        jMenuItem_nouveau_paiement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_nouveau_paiement.setText("Nouveau paiement");
        jMenuItem_nouveau_paiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nouveau_paiementActionPerformed(evt);
            }
        });
        jMenu_paiement.add(jMenuItem_nouveau_paiement);

        jMenuItem_historique_paiement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_historique_paiement.setText("Historique des paiements");
        jMenu_paiement.add(jMenuItem_historique_paiement);

        jMenuBar1.add(jMenu_paiement);

        jMenu_a_propos.setText("A propos");
        jMenuBar1.add(jMenu_a_propos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_personnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_personnelActionPerformed
         this.setContentPane(new PersonnelPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_personnelActionPerformed

    private void jMenuItem_avantage_en_natureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_avantage_en_natureActionPerformed
        this.setContentPane(new AvantageEnNaturePanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_avantage_en_natureActionPerformed

    private void jMenuItem_taux_abattementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_taux_abattementActionPerformed
        this.setContentPane(new AbattementPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_taux_abattementActionPerformed

    private void jMenuItem_renumerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_renumerationActionPerformed
        this.setContentPane(new RenumerationPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_renumerationActionPerformed

    private void jMenuItem_nouveau_paiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nouveau_paiementActionPerformed
        this.setContentPane(new NouveauPaiementPanel());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jMenuItem_nouveau_paiementActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AdministrationTypeRenumeration kk=new AdministrationTypeRenumeration(null, rootPaneCheckingEnabled);
                  kk.setVisible( rootPaneCheckingEnabled);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_avantage_en_nature;
    private javax.swing.JMenuItem jMenuItem_historique_paiement;
    private javax.swing.JMenuItem jMenuItem_nouveau_paiement;
    private javax.swing.JMenuItem jMenuItem_personnel;
    private javax.swing.JMenuItem jMenuItem_renumeration;
    private javax.swing.JMenuItem jMenuItem_taux_abattement;
    private javax.swing.JMenu jMenu_a_propos;
    private javax.swing.JMenu jMenu_edition;
    private javax.swing.JMenu jMenu_fichier;
    private javax.swing.JMenu jMenu_paiement;
    private rojerusan.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables
}
